## 1.특정 열을 행 인덱스로 설정
DataFrame.set_index(['열 이름'] or '열 이름')

In [1]:
import pandas as pd

exam_data = {'이름': ['성욱', '솔아', '상정', '진영'],
             '수학': [90, 70, 75, 80],
             '영어': [70, 68, 90, 75],
             '국어': [80, 95, 70, 80],
             '과학': [95, 60, 86, 90]}

df = pd.DataFrame(exam_data)
print(f'DataFrame:\n{df}\n')

df = df.set_index('이름')
print(f'DataFrame:\n{df}\n')

df = df.set_index(['수학'])
print(f'DataFrame:\n{df}\n')

df = df.set_index(['영어', '국어'])
print(f'DataFrame:\n{df}')

DataFrame:
   이름  수학  영어  국어  과학
0  성욱  90  70  80  95
1  솔아  70  68  95  60
2  상정  75  90  70  86
3  진영  80  75  80  90

DataFrame:
    수학  영어  국어  과학
이름
성욱  90  70  80  95
솔아  70  68  95  60
상정  75  90  70  86
진영  80  75  80  90

DataFrame:
    영어  국어  과학
수학
90  70  80  95
70  68  95  60
75  90  70  86
80  75  80  90

DataFrame:
       과학
영어 국어
70 80  95
68 95  60
90 70  86
75 80  90

## 2.행 인덱스 재배열
DataFrame.reindex(새로운 인덱스 배열)

In [2]:
import pandas as pd

dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index = ['r0','r1','r2'])
print(f'DataFrame:\n{df}\n')

df2 = df.reindex(['r0','r1','r2','r3','r4'])
print(f'DataFrame:\n{df2}\n')

df3 = df.reindex(['r0','r1','r2','r3','r4'], fill_value=0)
print(f'DataFrame:\n{df3}')

DataFrame:
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

DataFrame:
     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

DataFrame:
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

## 3.행 인덱스 초기화
DataFrame.reset_index()

In [3]:
import pandas as pd

dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
print(f'DataFrame:\n{df}\n')

df = df.reset_index()
print(f'DataFrame:\n{df}')

DataFrame:
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

DataFrame:
  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

## 4.행 인덕스를 기준으로 데이터프레임 정렬
DataFrame.sort_index(ascending = True or False)

In [4]:
import pandas as pd

dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
print(f'DataFrame:\n{df}\n')

df = df.sort_index(ascending=False) # (True: 오름차순, False: 내림차순)
print(f'DataFrame:\n{df}')

DataFrame:
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

DataFrame:
    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

## 5.특정 열의 데이터 값을 기준으로 데이터프레임 정렬
DataFrame.sort_values(by = '열 이름', ascending = True or False)

In [5]:
import pandas as pd

dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
print(f'DataFrame:\n{df}\n')

df = df.sort_values(by='c1', ascending=False)
print(f'DataFrame:\n{df}')

DataFrame:
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

DataFrame:
    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13