In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1.데이터 내용 미리보기

In [2]:
import pandas as pd

# 데이터 불러오기
file_path = '/content/drive/MyDrive/github/딥러닝을 위한 파이썬/Pandas/data/05000266/part3/auto-mpg.csv'
df = pd.read_csv(file_path)

# 데이터 프레임 컬럼명 지정
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name']

# 첫 5행 보기
print(df.head(),'\n')

# 마지막 5행 보기
print(df.tail())

    mpg  cylinders  displacement  ... model_year  origin                name
0  15.0          8         350.0  ...         70       1   buick skylark 320
1  18.0          8         318.0  ...         70       1  plymouth satellite
2  16.0          8         304.0  ...         70       1       amc rebel sst
3  17.0          8         302.0  ...         70       1         ford torino
4  15.0          8         429.0  ...         70       1    ford galaxie 500

[5 rows x 9 columns]

      mpg  cylinders  displacement  ... model_year  origin             name
392  27.0          4         140.0  ...         82       1  ford mustang gl
393  44.0          4          97.0  ...         82       2        vw pickup
394  32.0          4         135.0  ...         82       1    dodge rampage
395  28.0          4         120.0  ...         82       1      ford ranger
396  31.0          4         119.0  ...         82       1       chevy s-10

[5 rows x 9 columns]

## 2.데이터 요약 정보 확인

In [3]:
import pandas as pd

# 데이터 불러오기
file_path = '/content/drive/MyDrive/github/딥러닝을 위한 파이썬/Pandas/data/05000266/part3/auto-mpg.csv'
df = pd.read_csv(file_path)

# 데이터프레임 컬럼명 지정
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name']

# 데이터프레임 크기(행, 열) 확인
print(f'df.shape: {df.shape}\n')

# 데이터 프레임 기본 정보
print({df.info()},'\n')

# 데이터 프레임 자료형 확인
print(f'df.dtypes:\n{df.dtypes}\n')

# 열의 자료형 확인
print(f'df["mpg"].dtypes: {df["mpg"].dtypes}\n')

# 데이터 프레임 기술 통계 정보 확인(산술 데이터)
print(f'df.describe:\n{df.describe()}\n')

# 데이터 프레임 기술 통계 정보 확인(열에 대한 정보)
print(f'df.describe(include="all"):\n{df.describe(include="all")}')

df.shape: (397, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object
 4   weight        397 non-null    float64
 5   acceleration  397 non-null    float64
 6   model_year    397 non-null    int64
 7   origin        397 non-null    int64
 8   name          397 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.0+ KB
{None}

df.dtypes:
mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
name             object
dtype: object

df["mpg"].dtypes: float64

df.describe:
              mpg   cylinders  ...  model_year      origin
count  397.000000  397.000000  ...  397.000000  397.000000
mean    23.528463    5.448363  ...   76.025189    1.574307
std      7.820926    1.698329  ...    3.689922    0.802549
min      9.000000    3.000000  ...   70.000000    1.000000
25%     17.500000    4.000000  ...   73.000000    1.000000
50%     23.000000    4.000000  ...   76.000000    1.000000
75%     29.000000    8.000000  ...   79.000000    2.000000
max     46.600000    8.000000  ...   82.000000    3.000000

[8 rows x 7 columns]

df.describe(include="all"):
               mpg   cylinders  ...      origin        name
count   397.000000  397.000000  ...  397.000000         397
unique         NaN         NaN  ...         NaN         305
top            NaN         NaN  ...         NaN  ford pinto
freq           NaN         NaN  ...         NaN           6
mean     23.528463    5.448363  ...    1.574307         NaN
std       7.820926    1.698329  ...    0.802549         NaN
min       9.000000    3.000000  ...    1.000000         NaN
25%      17.500000    4.000000  ...    1.000000         NaN
50%      23.000000    4.000000  ...    1.000000         NaN
75%      29.000000    8.000000  ...    2.000000         NaN
max      46.600000    8.000000  ...    3.000000         NaN

[11 rows x 9 columns]

## 3.데이터 개수 확인

In [4]:
import pandas as pd

# 데이터 불러오기
file_path = '/content/drive/MyDrive/github/딥러닝을 위한 파이썬/Pandas/data/05000266/part3/auto-mpg.csv'
df = pd.read_csv(file_path)

# 데이터프레임 컬럼명 지정
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name']

# 데이터 프레임 각 열의 원소 개수
print(f'df.count:\n{df.count()}, type: {type(df.count())}\n')

# 열의 고유값(unique) 개수
print(f"df['cylinders'].value_counts():\n{df['cylinders'].value_counts()}")

df.count:
mpg             397
cylinders       397
displacement    397
horsepower      397
weight          397
acceleration    397
model_year      397
origin          397
name            397
dtype: int64, type: <class 'pandas.core.series.Series'>

df['cylinders'].value_counts():
4    204
8    102
6     84
3      4
5      3
Name: cylinders, dtype: int64